# Generated by Django 4.2.6 on 2023-10-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_endereco_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='fornecedores',
        ),
    ]
